<?php
declare(strict_types=1);

return [
    'euCountries' => [
        'AT',
        'BE',
        'BG',
        'CY',
        'CZ',
        'DE',
        'DK',
        'EE',
        'ES',
        'FI',
        'FR',
        'GR',
        'HR',
        'HU',
        'IE',
        'IT',
        'LT',
        'LU',
        'LV',
        'MT',
        'NL',
        'PO',
        'PT',
        'RO',
        'SE',
        'SI',
    ],
    'binApiUrl' => 'https://lookup.binlist.net/',
    'ratesApiUrl' => 'http://api.exchangeratesapi.io/latest',
    'ratesApiKey' => '8a66d88c0d6321b32a0c4254dba3d951',
    'defaultCurrency' => 'EUR',
    'euCoefficient' => 0.01,
    'nonEuCoefficient' => 0.02,
];
